- name: Install mysql
  apt: pkg={{item}}
  with_items:
  - mysql-server-5.6
  - libmysqlclient-dev
  - python-mysqldb
  sudo: yes
- name: copy minimal-memory.cnf
  copy: src=minimal-memory.cnf dest=/etc/mysql/conf.d
  notify: restart mysql
  sudo: yes
- name: create mysql db
  mysql_db: name={{user}} state=present
  sudo: yes
- name: create mysql user
  mysql_user: name={{user}} password={{user}} priv={{user}}.*:ALL state=present
  sudo: yes
- name: create mysql user {{os_user_name}}@%
  mysql_user: name={{user}} host=% password={{user}} priv={{user}}.*:ALL state=present
  sudo: yes
